version: 2.1
jobs:
  build:
    working_directory: ~/app
    environment:
      JWT_SECRET: "9876543456789876545678"
      REDIS_URL: "redis://localhost:6379"
    docker:
      - image: circleci/redis
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{checksum "package.json"}}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: yarn test
